#' Survival Curve(s)
#'
#' This function plots one or several survival curves for a given time-to-event model.
#'
#' @param fit An object of class \code{\link{survival{survfit}}.
#' @param fun An arbitrary function defining a transformation of the survival
#'   curve(s). Common transformations can be specified with a character argument,
#'   e.g. \code{"event"} for cumulative events (\eqn{f(y) = 1 - y}), \code{"cumhaz"}
#'   for the cumulative hazard function (\eqn{f(y) = -}log(\eqn{y})), and \code{"pct"}
#'   for survival probability in percentage.
#' @param CI Plot confidence intervals?
#' @param xlim Numeric vector of length two specifying x-axis limits.
#' @param ylim Numeric vector of length two specifying y-axis limits.
#' @param x.breaks Numeric value controlling x-axis breaks.
#' @param y.breaks Numeric value controlling y-axis breaks.
#' @param title Optional plot title.
#' @param legend Legend position. Must be one of \code{"outside",
#'   "bottomleft", "bottomright", "topleft",} or \code{"topright"}.
#' @param ... Additional arguments to be passed to \code{\link[survminer]{ggsurvplot}}.
#'
#' @details
#' Survival curves visualize the fit of a given time-to-event model, e.g. a
#' Kaplan-Meier estimator or a Cox proportional hazards regression. They are an
#' essential tool in survival analysis, providing a simple and intuitive visual
#' summary of the relative risk associated with various conditions.
#'
#' \code{plot_survival} is a stripped down wrapper for the \code{
#' \link[survminer]{ggsurvplot}} function from the \code{survminer} package, which
#' offers an impressive array of customization options for plotting survival curves.
#' \code{plot_survival} alters the default output of \code{ggsurvplot} to align it
#' with that of other figures generated by \code{bioplotr}, but you can override those
#' settings and/or take advantage of extra \code{ggsurvplot} functionalities by
#' passing additional arguments to \code{plot_survival}.
#'
#' @references
#' Andersen, P. & Gill, R. (1982). Cox's regression model for counting processes, a
#' large sample study. \emph{Annals of Statistics}, \strong{10}, 1100-1120.
#' \url{https://www.jstor.org/stable/2240714?seq=1#page_scan_tab_contents}
#'
#' Cox, D.R. (1972). Regression Models and Life-Tables. \emph{J. R. Stat. Soc.,
#' Series B}, \emph{34}(2): 187-220.
#' \url{https://www.jstor.org/stable/2985181?seq=1#page_scan_tab_contents}
#'
#' Kaplan, E.L. & Meier, P. (1958). Nonparametric estimation from incomplete
#' observations. \emph{J. Amer. Stat. Assn}, \emph{53}(282): 457-481.
#' \url{https://www.jstor.org/stable/2281868?seq=1#page_scan_tab_contents}
#'
#' @examples
#' library(survival)
#' fit <- survfit(Surv(time, status) ~ sex, data = lung)
#' plot_survival(fit)
#'
#' @export
#' @importFrom ggsci pal_d3
#' @import survminer

plot_survival <- function(fit,
                          fun = NULL,
                           CI = FALSE,
                         xlim = NULL,
                         ylim = NULL,
                     x.breaks = NULL,
                     y.breaks = NULL,
                        title = NULL,
                       legend = 'outside',
                          ...) {
  # Preliminaries
  if(!inherits(fit, 'survfit')) {
    stop('fit must be an object of class survfit. Load the survival package and see ',
         '?survfit for more details.')
  }
  if (!legend %in% c('outside', 'bottomleft', 'bottomright', 'topleft', 'topright')) {
    stop('legend must be one of "outside", "bottomleft", "bottomright", ',
         '"topleft", or "topright".')
  }

  # Tidy data
  df <- suppressWarnings(surv_summary(fit))
  if ('strata' %in% colnames(df)) {
    strata <- length(unique(df$strata))
  } else {
    strata <- 1L
  }
  if (is.null(title)) {
    if (strata > 1L) {
      title <- 'Survival Curves'
    } else {
      title <- 'Survival Curve'
    }
  }
  if (legend == 'outside') {
    legend <- 'right'
  } else if (legend == 'bottomleft') {
    legend <- c(0.01, 0.01)
  } else if (legend == 'bottomright') {
    legend <- c(0.99, 0.01)
  } else if (legend == 'topleft') {
    legend <- c(0.01, 0.99)
  } else if (legend == 'topright') {
    legend <- c(0.99, 0.99)
  }

  # Build plot
  ggsurvplot(fit, data = df, fun = fun, conf.int = CI, palette = pal_d3(strata),
             title = title, legend = legend, font.tickslab = 9,
             break.x.by = x.breaks, break.y.by = y.breaks, ...)

}
